apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoguard-operator
rules:
  - apiGroups: ["demoguard.dev"]
    resources: ["demopolicies", "demopolicies/status", "demoreadinesses", "demoreadinesses/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
