apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoguard-operator
rules:
  - apiGroups: ["demoguard.dev"]
    resources: ["demopolicies"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["demoguard.dev"]
    resources: ["demoreadinesses"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["demoguard.dev"]
    resources: ["demoreadinesses/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
